apiVersion: v1
kind: Pod
metadata:
  name: cart-app-pod
  namespace: pooja-ns
spec:
  containers:
    - name: test-container
      image: docker pull pnaik599/rcbimage:v1
      ports:
        - containerPort: 3015